### ISSUE TITLE
When applying cuts in Plotter, >= does not work as expected

### ISSUE THREAD

**Issue by Bryancaraway** [susy2015/ZInvisible#203] opened 2019-07-16 21:54 UTC
For example, if "nResolvedTops_drLeptonCleaned>=2" is passed through, the result is equivalent to nResolvedTops_drLeptonCleaned>=1. A unexpected bug.
A workaround is obviously requiring "nResolvedTops_drLeptonCleaned>1" which gives the desired result.

The relevant code can be found here:
https://github.com/susy2015/ZInvisible/blob/master/Tools/Plotter.cc#L613-L632

**Comment by caleb-james-smith** [comment] 2019-07-25 22:09
Hmm, I have used strings like this (see link).

https://github.com/susy2015/ZInvisible/blob/PhotonCR/Tools/MakePlots.C#L649-L662

```
";nBottoms_drLeptonCleaned>=1;nSoftBottoms_drLeptonCleaned>=1"
";nBottoms_drLeptonCleaned>=2"
```

**Comment by caleb-james-smith** [comment] 2019-08-19 16:27
Ok, I think I reproduced this problem... I got 0 events when trying to use "nBottoms_drLeptonCleaned>=1" .

**Comment by caleb-james-smith** [comment] 2019-08-19 19:02
The bug is here: https://github.com/susy2015/ZInvisible/blob/master/Tools/Plotter.cc#L617-L635

The problem is that both ">" and "=" appear in ">=", and likewise "<" and "=" appear in "<=".

**Comment by caleb-james-smith** [comment] 2019-08-19 19:04
One solution could be to first check for ">=" and "<=" before checking for ">", "<" and "=".

**Comment by caleb-james-smith** [comment] 2019-08-19 21:10
PR with fix: https://github.com/susy2015/ZInvisible/pull/209

**Comment by caleb-james-smith** [comment] 2019-08-20 13:30
PR merged to master (with data card updates): https://github.com/susy2015/ZInvisible/pull/210

**Closed as completed** 2019-08-20 13:30 UTC
Labels: bug
